AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an IAM user with EC2, S3, and IAM full access

Resources:
  IAMUser:
    Type: 'AWS::IAM::User'
    Properties: 
      UserName: 'AutomationUser'

  IAMUserAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties: 
      UserName: !Ref IAMUser

  IAMUserPolicy:
    Type: 'AWS::IAM::Policy'
    Properties: 
      PolicyName: 'AutomationUserPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action:
              - 'ec2:*'
              - 's3:*'
              - 'iam:*'
              - 'ssm:*'
            Resource: '*'
      Users: 
        - !Ref IAMUser

Outputs:
  AccessKeyId:
    Description: 'Access Key ID for IAM user'
    Value: !Ref 'IAMUserAccessKey'
    Export:
      Name: 'AccessKey'

  SecretAccessKey:
    Description: 'Secret Access Key for IAM user'
    Value: !GetAtt 'IAMUserAccessKey.SecretAccessKey'
    Export:
      Name: 'SecretKey'