- name: gno-node-setup
  hosts: all
  become: true
  remote_user: ubuntu
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_profile: default
    ansible_aws_ssm_bucket_name: gno-node-aws-ssm-connection-playbook
    ansible_aws_ssm_region: "eu-west-1"
  tasks:
    - name: pinging
      ping:

    - name: Install Git
      shell: |
        sudo yum update -y
        sudo yum install git -y
      register: result_git_install

    - name: Clone Gno
      shell: |
        cd ../../../../home/
        git clone https://github.com/gnolang/gno.git
      register: result_clone_gn 

    - name: Confirm Go instalation
      shell: |
        go version
      register: result_go_version
    
    - name: Build & Install Gnovm
      shell: |
        cd gno/gnovm
        make build
        make install
        gno --help
      register: result_gnovm

    - name: Build & Install Gnoland
      shell: |
        pwd
        cd gno/gno.land
        make build
        make install
      register: result_gnoland

    - name: Start Node
      shell: |
        pwd
        cd gno/gno.land
        nohup gnoland start
      register: result_start_node

    - name: Clone TxIndexer
      shell: |
        cd ../../../../home/
        git clone git clone https://github.com/gnolang/tx-indexer.git
      register: result_clone_supernova
 
    - name: Confirm Go instalation
      shell: |
        go version
      register: result_go_version
    
    - name: Build txindexer
      shell: |
        cd tx-indexer/
        make build
      register: result_txindexer_build

    - name: Run txindexer
      shell: |
       nohupecho usegrouvars
      register: result_txindexer

    - name: Clone SuperNova
      shell: |
        cd ../../../../home/
        git clone https://github.com/gnolang/supernova.git
      register: result_clone_supernova
 
    - name: Confirm Go instalation
      shell: |
        go version
      register: result_go_version
    
    - name: Build SuperNova
      shell: |
        cd supernova/
        make build
      register: result_supernova_build

    - name: Run SuperNova
      shell: |
       nohup echo usegrouvars
      register: result_supernova
