- name: supernova-setup
  hosts: supernova
  roles:
     - role: gantsign.golang
       golang_gopath: '$HOME/workspace-go'
  become: true
  remote_user: ubuntu
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_profile: default
    ansible_aws_ssm_bucket_name: supernova-aws-ssm-connection-playbook
    ansible_aws_ssm_region: "eu-west-1"
  tasks:
    - name: pinging
      ping:

    - name: Clone SuperNova
      shell: |
        cd ../../../../home/
        git clone https://github.com/gnolang/supernova.git
      register: result_clone_supernova
 
    - name: Confirm Go instalation
      shell: |
        go version
      register: result_go_version
    
    - name: Build SuperNova
      shell: |
        cd supernova/
        make build
      register: result_supernova_build

    - name: Run SuperNova
      shell: |
       echo usegrouvars
      register: result_supernova
